# Generated by Django 5.2 on 2025-05-09 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма сборки')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная сборка')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверена')),
                ('compatibility_errors', models.JSONField(blank=True, default=dict, verbose_name='Ошибки совместимости')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('components', models.ManyToManyField(limit_choices_to={'is_active': True}, through='configurator.BuildComponent', to='products.product', verbose_name='Компоненты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сборка ПК',
                'verbose_name_plural': 'Сборки ПК',
            },
        ),
        migrations.AddField(
            model_name='buildcomponent',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.pcbuild'),
        ),
        migrations.CreateModel(
            name='BuildComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='configurator.pcbuild')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='configurator.pcbuild')),
            ],
            options={
                'unique_together': {('build', 'user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='buildcomponent',
            unique_together={('build', 'product')},
        ),
    ]
