# Generated by Django 5.2 on 2025-05-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название сборки'),
        ),
    ]
