from .case import CaseSpecs
from .casefan import CaseFanSpecs
from .cooler import CoolerSpecs
from .hdd import HardDriveSpecs
from .m2ssd import M2SSDSpecs
from .motherboard import MotherboardSpecs
from .processor import ProcessorSpecs
from .psu import PSUSpecs
from .ram import RAMSpecs
from .ssd import SSDSpecs
from .thermalpaste import ThermalPasteSpecs
from .videocard import VideoCardSpecs
from .watercooling import WaterCoolingSpecs
